# Site settings
title: Ezinne Kalu
description: Writing about all the things that interest me. Hack, Stack and Hustle always.
author: Ezinne Kalu
baseurl: ""
url: "https://ezinnekalu.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title.html

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md